services:
  db:
    image: postgres:15
    restart: always
    container_name: dictionary-builder-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dictionary_builder_database
    ports:
      - "5438:5432"
    volumes:
      - dictionary-builder-postgres-data:/var/lib/postgresql/data
    networks:
      - custom

  backend:
    container_name: dictionary-builder-backend
    env_file:
      - ./.env
    volumes:
      - ./keystore.p12:/etc/dictionary-builder-secrets/keystore.p12
      - ./secretkey-256.bin:/etc/dictionary-builder-secrets/secretkey-256.bin
    build:
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8443:8443"
    networks:
      - custom

  redis:
    image: redis:7.2.5
    container_name: dictionary-builder-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - dictionary-builder-redis-data:/data
    networks:
      - custom

  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: dictionary-builder-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - custom
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:10.1.9
    container_name: dictionary-builder-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password
    ports:
      - "4000:3000"
    volumes:
      - dictionary-builder-grafana-data:/var/lib/grafana
    networks:
      - custom
    depends_on:
      - backend

volumes:
  dictionary-builder-postgres-data:
    name: dictionary-builder-postgres-data
  dictionary-builder-redis-data:
    name: dictionary-builder-redis-data
  dictionary-builder-grafana-data:
    name: dictionary-builder-grafana-data
  dictionary-builder-secrets:
    name: dictionary-builder-secrets

networks:
  custom:
    driver: bridge

