server:
  port: 8080
  servlet.context-path: /api/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5438/vocabulary_database}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      show_sql: false
      use_sql_comments: false
      format_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER}
    password: ${MAIL_SENDER_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  messages:
    basename: messages
logging:
  level:
    org.springframework.security: DEBUG
vocabulary:
  email.sender.context:
    registration:
      from: ${MAIL_SENDER}
      subject: "Please verify your registration"
      template-location: email/confirm-registration.html
      confirmation-url: http://localhost/signup/activate?verificationToken=
  user:
    preference:
      right-answers-to-disable-in-repetition: ${RIGHT_ANSWERS_TO_DISABLE_IN_REPETITION:10}
  jwt:
    secret-key-path: ${JWE_SECRET_KEY_PATH:secretkey-256.bin}
    jwe-algorithm: ${JWE_ALGORITHM:dir}
    jwe-encryption-method: ${JWE_ENCRYPTION_METHOD:A256GCM}
    access-expiration-time: ${JWE_ACCESS_EXPIRATION_TIME:1800}
    refresh-expiration-time: ${JWE_REFRESH_EXPIRATION_TIME:2419200}