server:
  port: 8443
  servlet.context-path: /api/v1
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: ${KEY_STORE_TYPE}
    key-alias: ${KEY_ALIAS}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5438/dictionary_builder_database}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      show_sql: true
      use_sql_comments: false
      format_sql: false
  security.oauth2.client.registration.google:
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}
    redirectUri: ${SERVER_URL:https://localhost:8443}/api/v1/login/oauth2/code/google
    scope:
      - profile
      - email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER}
    password: ${MAIL_SENDER_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  messages:
    basename: messages
  jackson:
    time-zone: UTC
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
logging:
  level:
    org.springframework.security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
vocabulary:
  email.sender.context:
    registration:
      from: ${MAIL_SENDER}
      subject: "Please verify your registration"
      template-location: email/confirm-registration.html
      confirmation-url: ${SERVER_URL:https://localhost:3000}/?verificationToken=
  user:
    profile:
      default-avatar: ${DEFAULT_AVATAR}
    preference:
      right-answers-to-disable-in-repetition: ${RIGHT_ANSWERS_TO_DISABLE_IN_REPETITION:10}
      words-per-page: ${WORDS_PER_PAGE:100}
      blur-translation: ${BLUR_TRANSLATION:true}
      new-words-per-day-goal: ${NEW_WORDS_PER_DAY_GOAL:10}
      daily-repetition-duration-goal: ${DAILY_REPETITION_DURATION_GOAL:1h}
  jwt:
    secret-key-path: ${JWE_SECRET_KEY_PATH:secretkey-128.bin}
    jwe-algorithm: ${JWE_ALGORITHM:dir}
    jwe-encryption-method: ${JWE_ENCRYPTION_METHOD:A128GCM}
    access-expiration-time: ${JWE_ACCESS_EXPIRATION_TIME:1800}
    refresh-expiration-time: ${JWE_REFRESH_EXPIRATION_TIME:2419200}
  repetition:
    words-to-update-count: ${WORDS_TO_UPDATE_COUNT:10}
config:
  mvc:
    allowed-origins: ${SERVER_URL:https://localhost:3000}
scheduler:
  pool-size: ${SCHEDULER_POOL_SIZE:10}
  thread-name-prefix: ${SCHEDULER_THREAD_NAME_PREFIX:scheduler-}
  start-task-delay: ${SCHEDULER_START_TASK_DELAY:PT10M}
  initial-delay: ${SCHEDULER_START_TASK_DELAY:PT10S}
retry:
  max-attempts: ${RETRY_MAX_ATTEMPTS:3}
  delay: ${RETRY_DELAY:1000}
swagger-server-url: ${SERVER_URL:https://localhost:8443}
post-oauth2-redirect-url: ${SERVER_URL:https://localhost:3000}/?token=%s
cipher:
  secret-key-path: ${CIPHER_SECRET_KEY_PATH:secretkey-128.bin}
  algorithm: ${CIPHER_ALGORITHM:AES}
  pool-size: ${CIPHER_POOL_SIZE:10}
