server:
  port: 8080
  servlet.context-path: /api/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/vocabulary_database
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      show_sql: false
      use_sql_comments: false
      format_sql: false
